version: "3.0"
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 6501:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo-5"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "mongo"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "123"
      ME_CONFIG_OPTIONS_EDITORTHEME: "rubyblue"
    networks:
      - webnet

networks:
  webnet:
    name: webnet
    external: true
