version: "3.0"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@a.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "15432:80"
    volumes:
      - ./data:/var/lib/pgadmin
    networks:
      - webnet

networks:
  webnet:
    name: webnet
    external: true
