version: "3.0"
services:
  postgres-14:
    image: postgres:14-alpine
    container_name: postgres-14
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet

networks:
  webnet:
    name: webnet
    external: true
